name: fn_http
description: Simple HTTP wrapper with clear outcomes directed through callbacks
version: 3.4.0
repository: https://github.com/suryavip/fn_http

environment:
  sdk: ^3.7.0

dependencies:
  cross_file: ^0.3.4+2
  http: ^1.2.2
  http_parser: ^4.0.2
  mime: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
