name: fn_http
description: Simple HTTP wrapper with clear outcomes directed through callbacks
version: 1.3.0
repository: https://github.com/suryavip/fn_http

environment:
  sdk: ^3.3.4

dependencies:
  http: ^1.2.1
  mime: ^1.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
